

USE ecommerce_analytics;

------------------------------------------------------------
-- 1. Top 10 Customers by Revenue
------------------------------------------------------------  

SELECT
    c.CustomerID,
    c.CustomerName,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM customers c
JOIN orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID,c.CustomerName
ORDER BY Revenue DESC
LIMIT 10;

------------------------------------------------------------
-- 2. Top 10 Selling Products
------------------------------------------------------------

SELECT
    p.ProductName,
    SUM(o.Quantity) AS QuantitySold
FROM products p
JOIN orders o
ON p.ProductID=o.ProductID
GROUP BY p.ProductName
ORDER BY QuantitySold DESC
LIMIT 10;

------------------------------------------------------------
-- 3. Revenue Generated by Each Product
------------------------------------------------------------

SELECT
    p.ProductName,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM products p
JOIN orders o
ON p.ProductID=o.ProductID
GROUP BY p.ProductName
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 4. Revenue by Product Category
------------------------------------------------------------

SELECT
    p.Category,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM products p
JOIN orders o
ON p.ProductID=o.ProductID
GROUP BY p.Category
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 5. Average Order Value
------------------------------------------------------------

SELECT
ROUND(AVG(TotalAmount),2) AS AverageOrderValue
FROM orders;

------------------------------------------------------------
-- 6. Total Revenue
------------------------------------------------------------

SELECT
ROUND(SUM(TotalAmount),2) AS TotalRevenue
FROM orders;

------------------------------------------------------------
-- 7. Total Revenue by Region
------------------------------------------------------------

SELECT
    c.Region,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.Region
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 8. Revenue by City
------------------------------------------------------------

SELECT
    c.City,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.City
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 9. Monthly Sales Trend
------------------------------------------------------------

SELECT
    MONTH(OrderDate) AS MonthNumber,
    ROUND(SUM(TotalAmount),2) AS Revenue
FROM orders
GROUP BY MONTH(OrderDate)
ORDER BY MonthNumber;

------------------------------------------------------------
-- 10. Orders by Status
------------------------------------------------------------

SELECT
    OrderStatus,
    COUNT(*) AS Orders
FROM orders
GROUP BY OrderStatus;

------------------------------------------------------------
-- 11. Average Quantity Purchased
------------------------------------------------------------

SELECT
ROUND(AVG(Quantity),2) AS AverageQuantity
FROM orders;

------------------------------------------------------------
-- 12. Customer Lifetime Value
------------------------------------------------------------

SELECT
    c.CustomerID,
    c.CustomerName,
    COUNT(o.OrderID) AS OrdersPlaced,
    ROUND(SUM(o.TotalAmount),2) AS CustomerLifetimeValue
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.CustomerID,c.CustomerName
ORDER BY CustomerLifetimeValue DESC;

------------------------------------------------------------
-- 13. Repeat Customers
------------------------------------------------------------

SELECT
    CustomerID,
    COUNT(OrderID) AS OrdersPlaced
FROM orders
GROUP BY CustomerID
HAVING COUNT(OrderID)>1
ORDER BY OrdersPlaced DESC;

------------------------------------------------------------
-- 14. Revenue by Gender
------------------------------------------------------------

SELECT
    c.Gender,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.Gender;

------------------------------------------------------------
-- 15. Revenue by Age Group
------------------------------------------------------------

SELECT
CASE
WHEN Age<25 THEN '18-24'
WHEN Age BETWEEN 25 AND 34 THEN '25-34'
WHEN Age BETWEEN 35 AND 44 THEN '35-44'
ELSE '45+'
END AS AgeGroup,
ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY AgeGroup
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 16. Campaign Performance
------------------------------------------------------------

SELECT
    ca.CampaignName,
    COUNT(o.OrderID) AS OrdersGenerated,
    ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM campaigns ca
JOIN orders o
ON ca.CampaignID=o.CampaignID
GROUP BY ca.CampaignName
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 17. Marketing ROI
------------------------------------------------------------

SELECT
    CampaignName,
    Budget,
    RevenueGenerated,
    ROUND(((RevenueGenerated-Budget)/Budget)*100,2) AS ROI_Percentage
FROM campaigns
ORDER BY ROI_Percentage DESC;

------------------------------------------------------------
-- 18. Highest Rated Products
------------------------------------------------------------

SELECT
    p.ProductName,
    ROUND(AVG(r.Rating),2) AS AverageRating
FROM products p
JOIN reviews r
ON p.ProductID=r.ProductID
GROUP BY p.ProductName
ORDER BY AverageRating DESC;

------------------------------------------------------------
-- 19. Review Distribution
------------------------------------------------------------

SELECT
Rating,
COUNT(*) AS TotalReviews
FROM reviews
GROUP BY Rating
ORDER BY Rating DESC;

------------------------------------------------------------
-- 20. Products with Most Reviews
------------------------------------------------------------

SELECT
    p.ProductName,
    COUNT(r.ReviewID) AS Reviews
FROM products p
JOIN reviews r
ON p.ProductID=r.ProductID
GROUP BY p.ProductName
ORDER BY Reviews DESC;

------------------------------------------------------------
-- 21. Return Rate by Product
------------------------------------------------------------

SELECT
    p.ProductName,
    COUNT(r.ReturnID) AS Returns
FROM products p
JOIN returns r
ON p.ProductID=r.ProductID
GROUP BY p.ProductName
ORDER BY Returns DESC;

------------------------------------------------------------
-- 22. Refund Status
------------------------------------------------------------

SELECT
RefundStatus,
COUNT(*) AS TotalReturns
FROM returns
GROUP BY RefundStatus;

------------------------------------------------------------
-- 23. Revenue by Payment Method
------------------------------------------------------------

SELECT
    PaymentMethod,
    ROUND(SUM(AmountPaid),2) AS Revenue
FROM payments
GROUP BY PaymentMethod
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 24. Successful Payments
------------------------------------------------------------

SELECT
PaymentStatus,
COUNT(*) AS TotalPayments
FROM payments
GROUP BY PaymentStatus;

------------------------------------------------------------
-- 25. Customers with Highest Average Order Value
------------------------------------------------------------

SELECT
    c.CustomerName,
    ROUND(AVG(o.TotalAmount),2) AS AverageOrder
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
GROUP BY c.CustomerName
ORDER BY AverageOrder DESC
LIMIT 10;

------------------------------------------------------------
-- 26. Most Purchased Brands
------------------------------------------------------------

SELECT
    p.Brand,
    SUM(o.Quantity) AS QuantitySold
FROM products p
JOIN orders o
ON p.ProductID=o.ProductID
GROUP BY p.Brand
ORDER BY QuantitySold DESC;

------------------------------------------------------------
-- 27. Most Expensive Products
------------------------------------------------------------

SELECT
ProductName,
SellingPrice
FROM products
ORDER BY SellingPrice DESC
LIMIT 10;

------------------------------------------------------------
-- 28. Average Product Price by Category
------------------------------------------------------------

SELECT
Category,
ROUND(AVG(SellingPrice),2) AS AveragePrice
FROM products
GROUP BY Category;

------------------------------------------------------------
-- 29. Customers without Returns
------------------------------------------------------------

SELECT DISTINCT
c.CustomerID,
c.CustomerName
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
LEFT JOIN returns r
ON o.OrderID=r.OrderID
WHERE r.ReturnID IS NULL;

------------------------------------------------------------
-- 30. Customers with Highest Number of Returns
------------------------------------------------------------

SELECT
c.CustomerName,
COUNT(r.ReturnID) AS Returns
FROM customers c
JOIN orders o
ON c.CustomerID=o.CustomerID
JOIN returns r
ON o.OrderID=r.OrderID
GROUP BY c.CustomerName
ORDER BY Returns DESC;

------------------------------------------------------------
-- 31. Revenue by Brand
------------------------------------------------------------

SELECT
Brand,
ROUND(SUM(o.TotalAmount),2) AS Revenue
FROM products p
JOIN orders o
ON p.ProductID=o.ProductID
GROUP BY Brand
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 32. Total Revenue per Customer
------------------------------------------------------------

SELECT
CustomerID,
ROUND(SUM(TotalAmount),2) AS Revenue
FROM orders
GROUP BY CustomerID
ORDER BY Revenue DESC;

------------------------------------------------------------
-- 33. Monthly Order Count
------------------------------------------------------------

SELECT
MONTH(OrderDate) AS MonthNumber,
COUNT(*) AS Orders
FROM orders
GROUP BY MONTH(OrderDate);

------------------------------------------------------------
-- 34. Average Customer Rating
------------------------------------------------------------

SELECT
ROUND(AVG(Rating),2) AS AverageRating
FROM reviews;

------------------------------------------------------------
-- 35. Total Products in Each Category
------------------------------------------------------------

SELECT
Category,
COUNT(*) AS Products
FROM products
GROUP BY Category;

------------------------------------------------------------
-- End of Business Queries
------------------------------------------------------------